console.log("01--------------------Declaration Of variable-----------------");
var myFullName;
console.log("My full Name is:-",myFullName);
console.log("01--------------------Inlizition Of variable-----------------");
 var myFullName="Satyavan shejal";
console.log("My Full Name is:-",myFullName);
console.log("01--------------------Update Of variable-----------------");
myFullName="satyavan Jagannath Shejal";
console.log("Updated Value of Variable myFullName is:-",myFullName);
console.log("02--------------------Declaration and Intilizition of variable-----------------");
var myLove="I love only Js";
console.log("Declaration and Intilizion of variable mylove is:-",myLove);
console.log("03--------------------Declaration Of variable of Form Controls-----------------");
var firstName="Satyavan";
console.log("First Name:",firstName);
var lastName="shejal";
console.log("Last Name:",lastName);
var age="27";
console.log("Age:",age);
var address="Save taluka sangola dist Solapur.";
console.log("Address:",address);
var pinCode="413317";
console.log("Pin Code:",pinCode);
var gender="male";
console.log("Gender:",gender);
var isMarried="Yes";
console.log("Is Married :",isMarried);
console.log("------------------------Thank You-----------------------");